//============================================================================
// main.c - DRIVER
//
// Reads the command line, then runs the pipeline for each input file:
//   C file -> [cc1: token.c -> preprocess.c -> parser.c -> cgen.c]
//          -> assembly -> asm.c (or `as`) -> object file
//          -> link.c (static) or `ld` (dynamic) -> executable
// mucc runs itself again as `mucc -cc1` to compile each C file.
//============================================================================

#include "mucc.h"


//---------- Command-line options --------------------------------------------

typedef enum {
  FILE_NONE, FILE_C, FILE_ASM, FILE_ASM_CPP, FILE_OBJ, FILE_AR, FILE_DSO,
} FileType;

StringArray include_paths;
bool opt_w; // -w: no warnings
StringArray opt_warnings; // -Wall, -Wno-format, ... without the -W, in order
bool opt_g; // -g: debug info for variables and types (see cgen.c)
bool opt_fcommon = true;
bool opt_fpic;
bool opt_asm_cpp; // preprocessing assembly (.S), not C
int opt_std = 2017; // -std=: 1989, 1999, 2011, 2017 or 2023 (C17 by default, as gcc 14)

static FileType opt_x; // the last -x, for the inputs after it
static StringArray opt_include;
static bool opt_E;
static bool opt_P;
static bool opt_M;
static bool opt_MD;
static bool opt_MD_driver; // -MD or -MMD itself, not through -Wp,
static bool opt_MMD;
static bool opt_MP;
static bool opt_S;
static bool opt_c;
static bool opt_cc1;
static bool opt_cc1_obj;               // cc1 writes an object, not assembly
static bool opt_integrated_as = true;  // -fno-integrated-as: run `as`
static bool opt_as_fallback = true;    // -fno-as-fallback: never run `as`
static bool opt_system_ld;             // -fuse-ld=...: always run `ld`
static bool opt_hash_hash_hash;
static bool opt_static;
static bool opt_shared;
static bool opt_pthread;       // -pthread: also link -lpthread
static bool opt_nostartfiles;  // -nostartfiles or -nostdlib: no crt*.o
static bool opt_nodefaultlibs; // -nodefaultlibs or -nostdlib: no libc
static bool opt_r;             // -r: link into an object file, as ld -r
static char *opt_MF;
static char *opt_MT;
static char *opt_o;

static StringArray ld_extra_args;
static StringArray std_include_paths;

char *base_file;
static char *output_file;

static StringArray input_paths;
static FileType *input_types; // the -x in effect for each input, as gcc does
static StringArray tmpfiles;
static HashMap object_sources; // temporary object file -> its C file

//---------- Embedded files --------------------------------------------------

// The single mucc binary (`make build/mucc`) carries its headers and the
// C library inside it: build/files.s, generated by the Makefile, defines
// this table with each file's bytes (by .incbin), ending with an entry
// whose path is NULL. Their paths start with EMBED_DIR, as in
// "<mucc>/musl/include/stdio.h", which is no real file, and they are read
// from memory. A mucc built without that file has this empty table.
typedef struct {
  char *path;
  char *data;
  size_t size;
} EmbeddedFile;

__attribute__((weak)) EmbeddedFile mucc_files[1];

#define EMBED_DIR "<mucc>"

static EmbeddedFile *find_embedded(char *path) {
  static HashMap map;
  if (strncmp(path, EMBED_DIR "/", strlen(EMBED_DIR) + 1))
    return NULL;
  if (!map.capacity)
    for (EmbeddedFile *f = mucc_files; f->path; f++)
      hashmap_put(&map, f->path, f);
  return hashmap_get(&map, path);
}

// Opens `path` for reading, from memory if it's embedded.
FILE *open_input_file(char *path) {
  EmbeddedFile *f = find_embedded(path);
  if (f)
    return fmemopen(f->data, f->size, "rb");
  return fopen(path, "rb");
}

//---------- Include paths and the C library (--libc) ------------------------

// Returns the directory containing the running mucc binary. argv[0] is
// only a bare "mucc" when mucc is found via $PATH, so ask the kernel.
static char *exe_dir(char *argv0) {
  char buf[4096];
  ssize_t n = readlink("/proc/self/exe", buf, sizeof(buf) - 1);
  if (n == -1)
    return dirname(strdup(argv0));
  buf[n] = '\0';
  return dirname(strdup(buf));
}

// Are `a` and `b` the same directory, under any spelling?
static bool same_dir(char *a, char *b) {
  struct stat st, st2;
  return !stat(a, &st) && !stat(b, &st2) && st.st_dev == st2.st_dev &&
         st.st_ino == st2.st_ino;
}

static bool in_include_paths(char *dir) {
  for (int i = 0; i < include_paths.len; i++)
    if (same_dir(include_paths.data[i], dir))
      return true;
  return false;
}

// A C library mucc compiles and links against: where its headers,
// startup files and libraries are, and what else to link. This is the
// only place with system paths. --libc=system is glibc as installed,
// with gcc's startup files and runtime library. --libc=mucc is the musl
// `make libc` builds, always linked statically, with nothing from gcc.
typedef struct {
  char *name;          // as in --libc=
  char **include_dirs; // its headers, searched after mucc's own
  char **crt_dirs;     // the first with crti.o has crt1.o, crti.o, crtn.o
  char **gcc_dirs;     // the first match has crtbegin.o, crtend.o, libgcc
  char **lib_dirs;     // searched for -l, after -L and the gcc directory
  char **static_libs;  // linked after the inputs with -static
  char **shared_libs;  // otherwise (in ld's syntax)
  char *dynamic_linker;
} Libc;

static char *system_include_dirs[] = {
  "/usr/local/include", "/usr/include/x86_64-linux-gnu", "/usr/include", NULL,
};
static char *system_crt_dirs[] = {
  "/usr/lib/x86_64-linux-gnu", "/usr/lib64", NULL,
};
static char *system_gcc_dirs[] = {
  "/usr/lib/gcc/x86_64-linux-gnu/*",
  "/usr/lib/gcc/x86_64-pc-linux-gnu/*", // Gentoo
  "/usr/lib/gcc/x86_64-redhat-linux/*", // Fedora
  NULL,
};
static char *system_lib_dirs[] = {
  "/usr/lib/x86_64-linux-gnu", "/usr/lib64", "/lib64",
  "/usr/lib/x86_64-pc-linux-gnu", "/usr/lib/x86_64-redhat-linux", "/usr/lib",
  "/lib", NULL,
};
static char *system_static_libs[] = {"-lgcc", "-lgcc_eh", "-lc", NULL};
static char *system_shared_libs[] = {
  "-lc", "-lgcc", "--as-needed", "-lgcc_s", "--no-as-needed", NULL,
};

// Filled in by find_musl(), next to the mucc binary.
static char *musl_include_dirs[2];
static char *musl_lib_dirs[2];
static char *no_dirs[] = {NULL};
static char *musl_static_libs[] = {"-lc", NULL};

static Libc libcs[] = {
  {"system", system_include_dirs, system_crt_dirs, system_gcc_dirs,
   system_lib_dirs, system_static_libs, system_shared_libs,
   "/lib64/ld-linux-x86-64.so.2"},
  {"mucc", musl_include_dirs, musl_lib_dirs, no_dirs, musl_lib_dirs,
   musl_static_libs, NULL, NULL},
};

// --libc=, or by default the one inside the binary (the single binary,
// build/mucc, has musl), else the system's. See main().
static Libc *libc;

static void set_libc(char *name) {
  for (int i = 0; i < sizeof(libcs) / sizeof(*libcs); i++) {
    if (!strcmp(libcs[i].name, name)) {
      libc = &libcs[i];
      return;
    }
  }
  error("unknown C library: --libc=%s", name);
}

// musl, as `make libc` builds it: inside the binary, in build/musl next
// to it when run from the source tree, or in ../lib/mucc/musl after
// `make install`, with its headers in include/ and crt1.o, crti.o,
// crtn.o and libc.a in lib/.
static void find_musl(char *argv0) {
  if (find_embedded(EMBED_DIR "/musl/lib/libc.a")) {
    musl_include_dirs[0] = EMBED_DIR "/musl/include";
    musl_lib_dirs[0] = EMBED_DIR "/musl/lib";
    return;
  }

  char *dir = format("%s/build/musl", exe_dir(argv0));
  if (!file_exists(format("%s/lib/libc.a", dir)))
    dir = format("%s/../lib/mucc/musl", exe_dir(argv0));
  if (!file_exists(format("%s/lib/libc.a", dir)))
    error("--libc=mucc: the C library isn't built; run `make libc`");

  // Its real path, the same through a symlink (as the Makefile's
  // stage2-musl/build is), since header paths go into the debug info.
  dir = realpath(dir, NULL);
  musl_include_dirs[0] = format("%s/include", dir);
  musl_lib_dirs[0] = format("%s/lib", dir);
}

static void add_default_include_paths(char *argv0) {
  // mucc's own headers are inside the binary, in ./include next to it
  // when run from the source tree, or in ../lib/mucc/include after
  // `make install`.
  char *dir = exe_dir(argv0);
  char *inc = format("%s/include", dir);
  if (find_embedded(EMBED_DIR "/include/stddef.h"))
    inc = EMBED_DIR "/include";
  else if (!file_exists(inc))
    inc = format("%s/../lib/mucc/include", dir);

  // mucc's headers and the C library's are the system headers: -MMD
  // leaves them out, and warnings and some type checks don't apply to
  // them. -I directories, added to include_paths before this runs, are
  // not.
  char **sys = libc->include_dirs;
  int nsys = 0;
  while (sys[nsys])
    nsys++;

  // As with gcc, -I of a system directory is ignored, and it's searched
  // in its place, after mucc's headers. (CPython's build passes
  // -I/usr/include/x86_64-linux-gnu, which put glibc's <sys/cdefs.h>
  // before mucc's, and glibc's then dropped every __attribute__.)
  StringArray user = include_paths;
  include_paths = (StringArray){};
  for (int i = 0; i < user.len; i++) {
    bool is_sys = false;
    for (int j = 0; j < nsys; j++)
      is_sys |= same_dir(user.data[i], sys[j]);
    if (!is_sys)
      strarray_push(&include_paths, user.data[i]);
  }

  // mucc's own headers, given with -I too (as the Makefile's -Iinclude
  // does), are searched once, where -I put them: listed twice,
  // include/sys/cdefs.h, which does #include_next of its own name, would
  // be read twice.
  if (!in_include_paths(inc))
    strarray_push(&include_paths, inc);
  strarray_push(&std_include_paths, inc);

  for (int i = 0; i < nsys; i++) {
    strarray_push(&include_paths, sys[i]);
    strarray_push(&std_include_paths, sys[i]);
  }
}

//---------- Argument parsing ------------------------------------------------

static void usage(int status) {
  fprintf(stderr, "mucc [ -o <path> ] <file>\n");
  exit(status);
}

static bool take_arg(char *arg) {
  char *x[] = {
    "-o", "-I", "-L", "-D", "-U", "-idirafter", "-isystem", "-include", "-x",
    "-MF", "-MT", "-Xlinker",
  };

  for (int i = 0; i < sizeof(x) / sizeof(*x); i++)
    if (!strcmp(arg, x[i]))
      return true;
  return false;
}

static void define(char *str) {
  char *eq = strchr(str, '=');
  if (eq)
    define_macro(strndup(str, eq - str), eq + 1);
  else
    define_macro(str, "1");
}

// Adds an input file (or -l, -Wl,), with the -x given before it.
static void add_input(char *path) {
  strarray_push(&input_paths, path);
  input_types = realloc(input_types, sizeof(FileType) * input_paths.len);
  input_types[input_paths.len - 1] = opt_x;
}

static FileType parse_opt_x(char *s) {
  if (!strcmp(s, "c"))
    return FILE_C;
  if (!strcmp(s, "assembler"))
    return FILE_ASM;
  if (!strcmp(s, "assembler-with-cpp"))
    return FILE_ASM_CPP;
  if (!strcmp(s, "none"))
    return FILE_NONE;
  error("<command line>: unknown argument for -x: %s", s);
}

static char *quote_makefile(char *s) {
  char *buf = calloc(1, strlen(s) * 2 + 1);

  for (int i = 0, j = 0; s[i]; i++) {
    switch (s[i]) {
    case '$':
      buf[j++] = '$';
      buf[j++] = '$';
      break;
    case '#':
      buf[j++] = '\\';
      buf[j++] = '#';
      break;
    case ' ':
    case '\t':
      for (int k = i - 1; k >= 0 && s[k] == '\\'; k--)
        buf[j++] = '\\';
      buf[j++] = '\\';
      buf[j++] = s[i];
      break;
    default:
      buf[j++] = s[i];
      break;
    }
  }
  return buf;
}

static bool is_std_option(char *arg) {
  return !strncmp(arg, "-std=", 5) || !strcmp(arg, "-ansi");
}

// -std=c17 or gnu17 and so on (the GNU and ISO modes are the same) sets
// opt_std. It's read before the other options, since predefined macros
// like __STDC_VERSION__ depend on it and -D and -U come after them.
static void set_std(int argc, char **argv) {
  static char *names[] = {"c89", "c90", "c99", "c9x", "c11", "c1x",
                          "c17", "c18", "c2x", "c23"};
  static int years[] = {1989, 1989, 1999, 1999, 2011, 2011, 2017, 2017, 2023, 2023};

  for (int i = 1; i < argc; i++) {
    if (!is_std_option(argv[i]))
      continue;
    char *s = argv[i][1] == 'a' ? "c89" : argv[i] + 5;
    if (!strncmp(s, "gnu", 3))
      s = format("c%s", s + 3);
    int k = 0;
    while (k < 10 && strcmp(s, names[k]))
      k++;
    if (k == 10)
      error("unsupported standard: %s", argv[i]);
    opt_std = years[k];
  }
}

// Options that only tune optimization, diagnostics or hardening, which
// a correct program doesn't depend on, so they're accepted and ignored.
// A name ending in '*' is a prefix.
static char *ignored_options[] = {
  "-O*", "-W", "-m64", "-mno-red-zone", "-pipe",
  "-pedantic", "-pedantic-errors",
  "-ffreestanding", "-fno-builtin*", "-fno-omit-frame-pointer",
  "-fomit-frame-pointer", "-fno-strict-aliasing", "-fstrict-aliasing",
  "-fstack-protector*", "-fno-stack-protector", "-fstack-clash-protection",
  "-fno-stack-clash-protection", "-fcf-protection*", "-fno-plt", "-fplt",
  "-fvisibility=*", "-ffunction-sections", "-fdata-sections",
  "-fno-function-sections", "-fno-data-sections",
  "-fwrapv", "-fno-strict-overflow", "-fno-delete-null-pointer-checks",
  "-fno-math-errno", "-fexceptions", "-fno-exceptions",
  "-funwind-tables", "-fno-unwind-tables", "-fasynchronous-unwind-tables",
  "-fno-asynchronous-unwind-tables", "-fdiagnostics-*", "-fmessage-length=*",
  "-fno-ident", "-fno-semantic-interposition", "-fsigned-char",
  "-fno-lto", "-flto*", "-fno-pie", "-fno-PIE", "-no-pie",
  // mucc makes non-PIE executables, which -fPIE objects would only be
  // linked into anyway.
  "-fpie", "-fPIE", "-pie",
  // Optimizations, which mucc doesn't do
  "-funroll-*", "-fno-unroll-*", "-finline*", "-fno-inline*", "-ftree-*",
  "-fno-tree-*", "-fexcess-precision=*", "-mfpmath=sse",
  // Paths in debug info and __FILE__, kept as they are
  "-ffile-prefix-map=*", "-fdebug-prefix-map=*", "-fmacro-prefix-map=*",
  // Hardening that has nothing to do in mucc's code, or that only gives
  // a value to what C leaves uninitialized
  "-fzero-call-used-regs=*", "-ftrivial-auto-var-init=*", "-mshstk",
  "-fstrict-flex-arrays*",
  // mucc needs no libgcc, and makes no LTO objects or record of options
  "-static-libgcc", "-ffat-lto-objects", "-fno-fat-lto-objects",
  "-frecord-gcc-switches", "-grecord-gcc-switches",
  "-save-temps*", "-fmax-errors=*",
};

static bool is_ignored_option(char *arg) {
  for (int i = 0; i < sizeof(ignored_options) / sizeof(*ignored_options); i++) {
    char *name = ignored_options[i];
    int len = strlen(name);
    if (name[len - 1] == '*' ? !strncmp(arg, name, len - 1) : !strcmp(arg, name))
      return true;
  }
  return false;
}

// -Wp,-MD,file and the like pass options to the preprocessor, which is
// mucc itself. (Linux's kbuild writes dependency files this way.)
static void parse_wp(char *arg) {
  StringArray opts = {};
  for (char *s = strtok(strdup(arg), ","); s; s = strtok(NULL, ","))
    strarray_push(&opts, s);

  for (int i = 0; i < opts.len; i++) {
    char *opt = opts.data[i];
    char *next = (i + 1 < opts.len) ? opts.data[i + 1] : NULL;
    if (!strcmp(opt, "-MD") || !strcmp(opt, "-MMD")) {
      opt_MD = true;
      opt_MMD = opt_MMD || !strcmp(opt, "-MMD");
      if (next && next[0] != '-') {
        opt_MF = next;
        i++;
      }
    } else if (!strcmp(opt, "-MF") && next) {
      opt_MF = next;
      i++;
    } else if (!strcmp(opt, "-MT") && next) {
      opt_MT = opt_MT ? format("%s %s", opt_MT, next) : next;
      i++;
    } else if (!strcmp(opt, "-MP")) {
      opt_MP = true;
    } else if (!strncmp(opt, "-D", 2) && opt[2]) {
      define(opt + 2);
    } else if (!strncmp(opt, "-U", 2) && opt[2]) {
      undef_macro(opt + 2);
    } else {
      error("unknown argument: -Wp,%s", arg);
    }
  }
}

static void parse_args(int argc, char **argv) {
  // Make sure that all command line options that take an argument
  // have an argument.
  for (int i = 1; i < argc; i++)
    if (take_arg(argv[i]))
      if (!argv[++i])
        usage(1);

  StringArray idirafter = {};
  StringArray isystem = {};
  bool opt_v = false;

  for (int i = 1; i < argc; i++) {
    if (!strcmp(argv[i], "-###")) {
      opt_hash_hash_hash = true;
      continue;
    }

    // Build tools ask which system the compiler targets, and its version.
    if (!strcmp(argv[i], "-dumpmachine") || !strcmp(argv[i], "-print-multiarch")) {
      printf("x86_64-linux-gnu\n");
      exit(0);
    }

    if (!strcmp(argv[i], "-dumpversion") || !strcmp(argv[i], "-dumpfullversion")) {
      printf("%s\n", MUCC_VERSION);
      exit(0);
    }

    // mucc has no separate files or programs to find, so the name is the
    // answer, as gcc gives it for one it doesn't have.
    if (!strncmp(argv[i], "-print-file-name=", 17) ||
        !strncmp(argv[i], "-print-prog-name=", 17)) {
      printf("%s\n", argv[i] + 17);
      exit(0);
    }

    // Prints the version, as configure scripts ask for. With no input
    // files, that's all.
    if (!strcmp(argv[i], "-v")) {
      opt_v = true;
      continue;
    }

    if (!strcmp(argv[i], "-cc1")) {
      opt_cc1 = true;
      continue;
    }

    if (!strcmp(argv[i], "--help"))
      usage(0);

    if (!strcmp(argv[i], "--version")) {
      printf("mucc %s\n", MUCC_VERSION);
      exit(0);
    }

    if (!strcmp(argv[i], "-o")) {
      opt_o = argv[++i];
      continue;
    }

    if (!strncmp(argv[i], "-o", 2)) {
      opt_o = argv[i] + 2;
      continue;
    }

    if (!strcmp(argv[i], "-S")) {
      opt_S = true;
      continue;
    }

    if (!strcmp(argv[i], "-fcommon")) {
      opt_fcommon = true;
      continue;
    }

    if (!strcmp(argv[i], "-fno-common")) {
      opt_fcommon = false;
      continue;
    }

    // Read by set_std(), before the predefined macros are made.
    if (is_std_option(argv[i]))
      continue;

    if (!strcmp(argv[i], "-c")) {
      opt_c = true;
      continue;
    }

    if (!strcmp(argv[i], "-E")) {
      opt_E = true;
      continue;
    }

    if (!strcmp(argv[i], "-P")) {
      opt_P = true;
      continue;
    }

    // -Idir or -I dir, as -D, -U and -L
    if (!strncmp(argv[i], "-I", 2)) {
      strarray_push(&include_paths, argv[i][2] ? argv[i] + 2 : argv[++i]);
      continue;
    }

    if (!strcmp(argv[i], "-D")) {
      define(argv[++i]);
      continue;
    }

    if (!strncmp(argv[i], "-D", 2)) {
      define(argv[i] + 2);
      continue;
    }

    if (!strcmp(argv[i], "-U")) {
      undef_macro(argv[++i]);
      continue;
    }

    if (!strncmp(argv[i], "-U", 2)) {
      undef_macro(argv[i] + 2);
      continue;
    }

    if (!strcmp(argv[i], "-include")) {
      strarray_push(&opt_include, argv[++i]);
      continue;
    }

    if (!strcmp(argv[i], "-x")) {
      opt_x = parse_opt_x(argv[++i]);
      continue;
    }

    if (!strncmp(argv[i], "-x", 2)) {
      opt_x = parse_opt_x(argv[i] + 2);
      continue;
    }

    if (!strncmp(argv[i], "-l", 2) || !strncmp(argv[i], "-Wl,", 4)) {
      add_input(argv[i]);
      continue;
    }

    if (!strcmp(argv[i], "-Xlinker")) {
      strarray_push(&ld_extra_args, argv[++i]);
      continue;
    }

    if (!strcmp(argv[i], "-s")) {
      strarray_push(&ld_extra_args, "-s");
      continue;
    }

    if (!strcmp(argv[i], "-M")) {
      opt_M = true;
      continue;
    }

    if (!strcmp(argv[i], "-MF")) {
      opt_MF = argv[++i];
      continue;
    }

    if (!strcmp(argv[i], "-MP")) {
      opt_MP = true;
      continue;
    }

    if (!strcmp(argv[i], "-MT")) {
      if (opt_MT == NULL)
        opt_MT = argv[++i];
      else
        opt_MT = format("%s %s", opt_MT, argv[++i]);
      continue;
    }

    if (!strcmp(argv[i], "-MD")) {
      opt_MD = opt_MD_driver = true;
      continue;
    }

    if (!strcmp(argv[i], "-MQ")) {
      if (opt_MT == NULL)
        opt_MT = quote_makefile(argv[++i]);
      else
        opt_MT = format("%s %s", opt_MT, quote_makefile(argv[++i]));
      continue;
    }

    if (!strcmp(argv[i], "-MMD")) {
      opt_MD = opt_MMD = opt_MD_driver = true;
      continue;
    }

    if (!strcmp(argv[i], "-fpic") || !strcmp(argv[i], "-fPIC")) {
      opt_fpic = true;
      continue;
    }

    if (!strcmp(argv[i], "-cc1-input")) {
      base_file = argv[++i];
      continue;
    }

    if (!strcmp(argv[i], "-cc1-output")) {
      output_file = argv[++i];
      continue;
    }

    if (!strcmp(argv[i], "-cc1-obj")) {
      opt_cc1_obj = true;
      continue;
    }

    if (!strcmp(argv[i], "-cc1-asm")) {
      opt_asm_cpp = true;
      continue;
    }

    if (!strcmp(argv[i], "-fintegrated-as")) {
      opt_integrated_as = true;
      continue;
    }

    if (!strcmp(argv[i], "-fno-integrated-as")) {
      opt_integrated_as = false;
      continue;
    }

    if (!strcmp(argv[i], "-fas-fallback")) {
      opt_as_fallback = true;
      continue;
    }

    if (!strcmp(argv[i], "-fno-as-fallback")) {
      opt_as_fallback = false;
      continue;
    }

    if (!strncmp(argv[i], "-fuse-ld=", 9)) {
      opt_system_ld = true;
      continue;
    }

    if (!strncmp(argv[i], "--libc=", 7)) {
      set_libc(argv[i] + 7);
      continue;
    }

    if (!strcmp(argv[i], "-idirafter")) {
      strarray_push(&idirafter, argv[++i]);
      continue;
    }

    // -isystem dir: searched after the -I directories, as a system
    // directory, whose headers get no warnings
    if (!strcmp(argv[i], "-isystem")) {
      strarray_push(&isystem, argv[++i]);
      continue;
    }

    if (!strcmp(argv[i], "-static")) {
      opt_static = true;
      strarray_push(&ld_extra_args, "-static");
      continue;
    }

    if (!strcmp(argv[i], "-shared")) {
      opt_shared = true;
      strarray_push(&ld_extra_args, "-shared");
      continue;
    }

    if (!strcmp(argv[i], "-L")) {
      strarray_push(&ld_extra_args, "-L");
      strarray_push(&ld_extra_args, argv[++i]);
      continue;
    }

    if (!strncmp(argv[i], "-L", 2)) {
      strarray_push(&ld_extra_args, "-L");
      strarray_push(&ld_extra_args, argv[i][2] ? argv[i] + 2 : argv[++i]);
      continue;
    }

    if (!strcmp(argv[i], "-w")) {
      opt_w = true;
      continue;
    }

    if (!strncmp(argv[i], "-Wp,", 4)) {
      parse_wp(argv[i] + 4);
      continue;
    }

    // As with gcc, -pthread defines _REENTRANT and links -lpthread (an
    // empty library in glibc 2.34 and later, and in musl).
    if (!strcmp(argv[i], "-pthread")) {
      define("_REENTRANT");
      opt_pthread = true;
      continue;
    }

    // Linking without the C library's startup files (crt1.o, ...) or its
    // libraries, for programs that bring their own _start.
    if (!strcmp(argv[i], "-r")) {
      opt_r = true;
      continue;
    }

    if (!strcmp(argv[i], "-nostdlib")) {
      opt_nostartfiles = opt_nodefaultlibs = true;
      continue;
    }

    if (!strcmp(argv[i], "-nostartfiles")) {
      opt_nostartfiles = true;
      continue;
    }

    if (!strcmp(argv[i], "-nodefaultlibs")) {
      opt_nodefaultlibs = true;
      continue;
    }

    // Exporting symbols for dlopen()ed modules: nothing to do in a static
    // program; see static_noop_flag().
    if (!strcmp(argv[i], "-rdynamic")) {
      add_input("-Wl,--export-dynamic");
      continue;
    }

    if (!strcmp(argv[i], "-hashmap-test")) {
      hashmap_test();
      exit(0);
    }

    // -g, -g3, -ggdb, ...: debug info for gdb. Line numbers are always
    // there; -g adds variables and types. -g0 turns it off again.
    if (!strncmp(argv[i], "-g", 2)) {
      opt_g = strcmp(argv[i], "-g0");
      continue;
    }

    // -Wall, -Werror, -Wno-unused-variable, ...: see warning_state() in
    // token.c. A name mucc doesn't have is accepted and does nothing.
    if (!strncmp(argv[i], "-W", 2) && argv[i][2]) {
      strarray_push(&opt_warnings, argv[i] + 2);
      continue;
    }

    if (is_ignored_option(argv[i]))
      continue;

    // mucc emits only baseline x86-64 instructions, which every x86-64
    // CPU runs, so a CPU choice like -march=native changes nothing.
    if (!strncmp(argv[i], "-march=", 7) || !strncmp(argv[i], "-mtune=", 7))
      continue;

    if (argv[i][0] == '-' && argv[i][1] != '\0')
      error("unknown argument: %s", argv[i]);

    add_input(argv[i]);
  }

  for (int i = 0; i < isystem.len; i++) {
    strarray_push(&include_paths, isystem.data[i]);
    strarray_push(&std_include_paths, isystem.data[i]);
  }
  for (int i = 0; i < idirafter.len; i++)
    strarray_push(&include_paths, idirafter.data[i]);

  if (opt_v && !opt_cc1) {
    fprintf(stderr, "mucc version %s\nTarget: x86_64-linux-gnu\n", MUCC_VERSION);
    if (input_paths.len == 0)
      exit(0);
  }

  if (input_paths.len == 0)
    error("no input files");
}

//---------- Output and temporary files --------------------------------------

static FILE *open_file(char *path) {
  if (!path || strcmp(path, "-") == 0)
    return stdout;

  FILE *out = fopen(path, "w");
  if (!out)
    error("cannot open output file: %s: %s", path, strerror(errno));
  return out;
}

static bool endswith(char *p, char *q) {
  int len1 = strlen(p);
  int len2 = strlen(q);
  return (len1 >= len2) && !strcmp(p + len1 - len2, q);
}

// Replace file extension
static char *replace_extn(char *tmpl, char *extn) {
  char *filename = basename(strdup(tmpl));
  char *dot = strrchr(filename, '.');
  if (dot)
    *dot = '\0';
  return format("%s%s", filename, extn);
}

static void cleanup(void) {
  for (int i = 0; i < tmpfiles.len; i++)
    unlink(tmpfiles.data[i]);
}

// A new temporary file, removed when mucc exits. It goes in $TMPDIR, or
// /tmp, or where mucc runs if there's no /tmp (as in an empty container),
// as with gcc.
static char *create_tmpfile(void) {
  char *dir = getenv("TMPDIR");
  if (!dir || !*dir)
    dir = file_exists("/tmp") ? "/tmp" : ".";
  char *path = format("%s/mucc-XXXXXX", dir);
  int fd = mkstemp(path);
  if (fd == -1)
    error("cannot create a temporary file %s: %s", path, strerror(errno));
  close(fd);

  strarray_push(&tmpfiles, path);
  return path;
}

//---------- Running other programs ------------------------------------------

static void run_subprocess(char **argv) {
  // If -### is given, dump the subprocess's command line.
  if (opt_hash_hash_hash) {
    fprintf(stderr, "%s", argv[0]);
    for (int i = 1; argv[i]; i++)
      fprintf(stderr, " %s", argv[i]);
    fprintf(stderr, "\n");
  }

  if (fork() == 0) {
    // Child process. Run a new command.
    execvp(argv[0], argv);
    fprintf(stderr, "exec failed: %s: %s\n", argv[0], strerror(errno));
    _exit(1);
  }

  // Wait for the child process to finish. If it crashed, say so: it
  // printed nothing itself. SIGPIPE isn't a crash: whatever read its
  // output stopped reading (`mucc -E x.c | head`).
  int status;
  while (wait(&status) > 0);
  if (WIFSIGNALED(status) && WTERMSIG(status) != SIGPIPE) {
    char *what = !strcmp(argv[0], "as") || !strcmp(argv[0], "ld") ? argv[0] : "mucc -cc1";
    fprintf(stderr, "mucc: internal error: %s crashed (%s)\n", what,
            strsignal(WTERMSIG(status)));
  }
  if (status != 0)
    exit(1);
}

// Runs `mucc -cc1` to compile `input`. It writes assembly to `output`,
// or, if `obj` is true, an object file (see cc1()).
// `asm_cpp`: the input is assembly to preprocess (.S), which cc1
// preprocesses into `output`.
static void run_cc1(int argc, char **argv, char *input, char *output, bool obj,
                    bool asm_cpp) {
  char **args = calloc(argc + 10, sizeof(char *));
  memcpy(args, argv, argc * sizeof(char *));
  args[argc++] = "-cc1";

  if (input) {
    args[argc++] = "-cc1-input";
    args[argc++] = input;
  }

  if (output) {
    args[argc++] = "-cc1-output";
    args[argc++] = output;
  }

  if (obj)
    args[argc++] = "-cc1-obj";
  if (asm_cpp)
    args[argc++] = "-cc1-asm";

  run_subprocess(args);
}

//---------- -E (preprocessed output) and -M (dependencies) ------------------

static bool in_std_include_path(char *path);

// Where -E's output is: the file being printed (its real name, and the
// name it is shown as, which #line can change), the line of it the output
// is on, and the files that included it.
static FILE *pp_out;
static char *pp_file;
static char *pp_name;
static int pp_line;
static StringArray pp_stack;

// Writes a line marker as gcc does: `# 12 "foo.h"`, plus flag 1 when
// entering an included file, 2 when returning to one, and 3 for a system
// header.
static void line_marker(char *file, char *name, int line) {
  int flag = 0;
  if (pp_file && strcmp(file, pp_file)) {
    flag = 1;
    for (int i = pp_stack.len - 1; i >= 0; i--) {
      if (!strcmp(pp_stack.data[i], file)) {
        pp_stack.len = i;
        flag = 2;
        break;
      }
    }
    if (flag == 1)
      strarray_push(&pp_stack, pp_file);
  }

  fprintf(pp_out, "# %d \"", line);
  for (char *p = name; *p; p++) {
    if (*p == '"' || *p == '\\')
      fputc('\\', pp_out);
    fputc(*p, pp_out);
  }
  fprintf(pp_out, "\"");
  if (flag)
    fprintf(pp_out, " %d", flag);
  if (in_std_include_path(file))
    fprintf(pp_out, " 3");
  fprintf(pp_out, "\n");

  pp_file = file;
  pp_name = name;
  pp_line = line;
}

// Moves the output to the start of `line` of a file, with a line marker
// unless a few newlines get there.
static void move_to(char *file, char *name, int line) {
  if (!strcmp(file, pp_file) && !strcmp(name, pp_name) &&
      pp_line < line && line - pp_line <= 8) {
    for (; pp_line < line; pp_line++)
      fprintf(pp_out, "\n");
    return;
  }
  fprintf(pp_out, "\n");
  line_marker(file, name, line);
}

// Print tokens for -E. Unless -P is given, line markers say where each
// line came from, so the output, compiled again, reports errors and debug
// info against the original files. A macro's expansion stays on the line
// of its name.
static void print_tokens(Token *tok, char *path) {
  pp_out = open_file(path);
  if (!opt_P)
    line_marker(base_file, base_file, 1);

  for (bool first = true; tok->kind != TK_EOF; tok = tok->next, first = false) {
    if (!tok->at_bol && !first) {
      if (tok->has_space)
        fprintf(pp_out, " ");
      fprintf(pp_out, "%.*s", tok->len, tok->loc);
      continue;
    }

    // Tokens in the output have had line_delta (#line) added already,
    // macro names they came from haven't.
    Token *src = tok;
    int line = tok->line_no;
    if (tok->origin) {
      while (src->origin)
        src = src->origin;
      line = src->line_no + src->line_delta;
    }

    if (opt_P || !src->filename) {
      if (!first) {
        fprintf(pp_out, "\n");
        pp_line++;
      }
    } else if (strcmp(src->file->name, pp_file) ||
               strcmp(src->filename, pp_name) || line != pp_line) {
      move_to(src->file->name, src->filename, line);
    } else if (!first) {
      fprintf(pp_out, " ");
    }
    fprintf(pp_out, "%.*s", tok->len, tok->loc);
  }
  fprintf(pp_out, "\n");
}

static bool in_std_include_path(char *path) {
  for (int i = 0; i < std_include_paths.len; i++) {
    char *dir = std_include_paths.data[i];
    int len = strlen(dir);
    if (strncmp(dir, path, len) == 0 && path[len] == '/')
      return true;
  }
  return false;
}

// True if `tok` was written in a system header such as /usr/include/stdio.h
// (possibly reaching the user's code through a macro), or, in -E output
// compiled again, after a line marker naming such a file.
bool in_system_header(Token *tok) {
  return in_std_include_path(tok->file->name) ||
         (tok->filename && in_std_include_path(tok->filename));
}

// Is file `name` listed by -M? Not a system header with -MMD, and never an
// embedded file, which make couldn't find.
static bool is_dependency(char *name) {
  return !(opt_MMD && in_std_include_path(name)) && !find_embedded(name);
}

// If -M options is given, the compiler write a list of input files to
// stdout in a format that "make" command can read. This feature is
// used to automate file dependency management.
static void print_dependencies(void) {
  char *path;
  if (opt_MF) {
    path = opt_MF;
  } else if (opt_MD && opt_o && opt_c) {
    // As with gcc, `-c -o obj/x.o` writes obj/x.d, next to the object.
    path = strdup(opt_o);
    char *dot = strrchr(path, '.');
    if (dot && !strchr(dot, '/'))
      *dot = '\0';
    path = format("%s.d", path);
  } else if (opt_MD) {
    path = replace_extn(opt_o ? opt_o : base_file, ".d");
  } else if (opt_o)
    path = opt_o;
  else
    path = "-";

  FILE *out = open_file(path);
  // The target: -MT's, or with -MD, -c and -o, the object, as gcc's
  // driver has it (`-c -o obj/x.o` is `obj/x.o:`), else the source's
  // name as an object, as the preprocessor's own -MD (-Wp,-MD) has it
  if (opt_MT)
    fprintf(out, "%s:", opt_MT);
  else if (opt_MD_driver && opt_o && opt_c)
    fprintf(out, "%s:", quote_makefile(opt_o));
  else
    fprintf(out, "%s:", quote_makefile(replace_extn(base_file, ".o")));

  File **files = get_input_files();

  for (int i = 0; files[i]; i++) {
    if (!is_dependency(files[i]->name))
      continue;
    fprintf(out, " \\\n  %s", files[i]->name);
  }

  fprintf(out, "\n");

  // As with gcc, -MP's targets are separated by blank lines, and the
  // file doesn't end with one (Linux's fixdep reads it line by line).
  if (opt_MP) {
    for (int i = 1; files[i]; i++) {
      if (!is_dependency(files[i]->name))
        continue;
      fprintf(out, "\n%s:\n", quote_makefile(files[i]->name));
    }
  }
}

//---------- Assembling: built in (asm.c), or with `as` ----------------------

static void run_as(char *input, char *output) {
  if (!opt_as_fallback)
    error("-fno-as-fallback and -fno-integrated-as can't be used together");
  char *cmd[] = {"as", "-c", input, "-o", output, NULL};
  run_subprocess(cmd);
}

static void write_file(char *path, char *buf, size_t len) {
  FILE *out = open_file(path);
  fwrite(buf, len, 1, out);
  fclose(out);
}

// Reads a file, or standard input if `path` is "-".
static char *read_whole_file(char *path, size_t *len) {
  FILE *fp = !strcmp(path, "-") ? stdin : fopen(path, "rb");
  if (!fp)
    error("%s: %s", path, strerror(errno));
  char *buf;
  FILE *out = open_memstream(&buf, len);
  char chunk[4096];
  size_t n;
  while ((n = fread(chunk, 1, sizeof(chunk), fp)) > 0)
    fwrite(chunk, 1, n, out);
  if (fp != stdin)
    fclose(fp);
  fclose(out);
  return buf;
}

// Assembles a .s file given on the command line. It may use anything,
// so if the built-in assembler doesn't know something, say so and use
// `as` (or stop, with -fno-as-fallback).
static void assemble_file(char *input, char *output) {
  if (!opt_integrated_as) {
    run_as(input, output);
    return;
  }

  size_t len;
  char *text = read_whole_file(input, &len);
  char *copy = strndup(text, len); // assemble_text() changes `text`
  char *why;
  if (assemble_text(text, output, &why))
    return;
  if (!opt_as_fallback)
    error("%s: the built-in assembler can't assemble this: %s", input, why);
  fprintf(stderr, "mucc: note: %s: using the system assembler (%s)\n", input, why);

  // The input may have been stdin, which is used up now.
  char *tmp = create_tmpfile();
  write_file(tmp, copy, len);
  run_as(tmp, output);
}

//---------- cc1: compile one C file to assembly -----------------------------

static Token *must_tokenize_file(char *path) {
  Token *tok = tokenize_file(path);
  if (!tok)
    error("%s: %s", path, strerror(errno));
  return tok;
}

static Token *append_tokens(Token *tok1, Token *tok2) {
  if (!tok1 || tok1->kind == TK_EOF)
    return tok2;

  Token *t = tok1;
  while (t->next->kind != TK_EOF)
    t = t->next;
  t->next = tok2;
  return tok1;
}

static void cc1(void) {
  Token *tok = NULL;

  // Process -include option
  for (int i = 0; i < opt_include.len; i++) {
    char *incl = opt_include.data[i];

    char *path;
    if (file_exists(incl)) {
      path = incl;
    } else {
      path = search_include_paths(incl);
      if (!path)
        error("-include: %s: %s", incl, strerror(errno));
    }

    Token *tok2 = must_tokenize_file(path);
    tok = append_tokens(tok, tok2);
  }

  // Assembly (.S) is only preprocessed, with __ASSEMBLER__ defined, as
  // gcc does; the driver assembles the output.
  if (opt_asm_cpp)
    define("__ASSEMBLER__");

  // Tokenize and parse.
  Token *tok2 = must_tokenize_file(base_file);
  tok = append_tokens(tok, tok2);
  tok = preprocess(tok);

  // If -M or -MD are given, print file dependencies.
  if (opt_M || opt_MD) {
    print_dependencies();
    if (opt_M)
      return;
  }

  // If -E is given, print out preprocessed C code as a result.
  if (opt_E || opt_asm_cpp) {
    print_tokens(tok, output_file ? output_file : opt_o ? opt_o : "-");
    return;
  }

  Obj *prog = parse(tok);
  if (error_count || werror_count)
    exit(1);

  // Open a temporary output buffer.
  char *buf;
  size_t buflen;
  FILE *output_buf = open_memstream(&buf, &buflen);

  // Traverse the AST to emit assembly.
  codegen(prog, output_buf);
  fclose(output_buf);

  if (!opt_cc1_obj) {
    write_file(output_file, buf, buflen);
    return;
  }

  // Assemble it right here. The built-in assembler knows everything
  // cgen.c writes, so a failure is a bug, unless it's an instruction in
  // an asm("...") statement; then fall back to `as` (or stop, with
  // -fno-as-fallback).
  char *copy = has_inline_asm ? strndup(buf, buflen) : NULL;
  char *why;
  if (assemble_text(buf, output_file, &why))
    return;
  if (!has_inline_asm)
    error("internal error in the built-in assembler: %s "
          "(-fno-integrated-as uses the system assembler instead)", why);
  if (!opt_as_fallback)
    error("%s: the built-in assembler can't assemble an asm statement: %s",
          base_file, why);

  char *tmp = create_tmpfile();
  write_file(tmp, copy, buflen);
  run_as(tmp, output_file);
}

//---------- Linking (ld) ----------------------------------------------------

static char *find_file(char *pattern) {
  char *path = NULL;
  glob_t buf = {};
  glob(pattern, 0, NULL, &buf);
  if (buf.gl_pathc > 0)
    path = strdup(buf.gl_pathv[buf.gl_pathc - 1]);
  globfree(&buf);
  return path;
}

// Returns true if a given file exists, on disk or embedded.
bool file_exists(char *path) {
  struct stat st;
  return find_embedded(path) || !stat(path, &st);
}

// Where the C library's crt1.o, crti.o and crtn.o are.
static char *find_libpath(void) {
  for (char **dir = libc->crt_dirs; *dir; dir++)
    if (file_exists(format("%s/crti.o", *dir)))
      return *dir;
  error("library path is not found");
}

// Where gcc's crtbegin.o, crtend.o and libgcc are (the latest version),
// or NULL for a C library that uses nothing from gcc.
static char *find_gcc_libpath(void) {
  if (!libc->gcc_dirs[0])
    return NULL;
  for (char **dir = libc->gcc_dirs; *dir; dir++) {
    char *path = find_file(format("%s/crtbegin.o", *dir));
    if (path)
      return dirname(path);
  }
  error("gcc library path is not found");
}

// Where libraries (libc.a, libgcc.a, ...) are searched, after -L dirs.
static void add_library_paths(StringArray *arr, char *gcc_libpath) {
  if (gcc_libpath)
    strarray_push(arr, gcc_libpath);
  for (char **dir = libc->lib_dirs; *dir; dir++)
    strarray_push(arr, *dir);
}

// Appends a NULL-terminated list of strings.
static void push_all(StringArray *arr, char **strs) {
  for (; *strs; strs++)
    strarray_push(arr, *strs);
}

// Appends gcc's startup file `name`, if the C library uses gcc's.
static void push_gcc_file(StringArray *arr, char *gcc_libpath, char *name) {
  if (gcc_libpath)
    strarray_push(arr, format("%s/%s", gcc_libpath, name));
}

// Linker flags that do nothing in a static program mucc's linker makes:
// dynamic linking options like -E (--export-dynamic, which Lua links
// with) and -rpath DIR (Tcl), grouping (it searches all archives as one
// group anyway), and hardening and size options build systems add, like
// --gc-sections and -z relro. A name ending in '*' is a prefix.
static char *static_noop_flags[] = {
  "-E", "--export-dynamic", "-export-dynamic", "-rpath=*", "--rpath=*",
  "--start-group", "--end-group", "-(", "-)", "--as-needed",
  "--no-as-needed", "--push-state", "--pop-state", "-Bstatic", "-Bdynamic",
  "-Bsymbolic*", "--gc-sections", "--no-gc-sections", "-O*", "--sort-common*",
  "--hash-style=*", "--build-id*", "--no-undefined", "--warn-common",
  "--enable-new-dtags", "--disable-new-dtags", "--eh-frame-hdr", "--relax",
  "--no-relax", "--fatal-warnings", "--no-copy-dt-needed-entries",
  "--compress-debug-sections=*", "--icf=*", "--version-script=*",
  "--verbose", "--sort-section=*",
};

// The `-z keyword`s among them. Others, like -z muldefs, change what
// links, so they need `ld`.
static char *static_noop_z[] = {
  "relro", "norelro", "now", "lazy", "noexecstack", "defs", "nodefs",
  "origin", "separate-code", "noseparate-code", "text", "combreloc",
  "nocombreloc", "max-page-size=*", "common-page-size=*", "ibt", "shstk",
  "cet-report=*",
};

static bool in_patterns(char *arg, char **names, int n) {
  for (int i = 0; i < n; i++) {
    int len = strlen(names[i]);
    if (names[i][len - 1] == '*' ? !strncmp(arg, names[i], len - 1)
                                 : !strcmp(arg, names[i]))
      return true;
  }
  return false;
}

// Returns how many arguments the flag at inputs[i] takes if it's one of
// static_noop_flags[] (or -z with one of static_noop_z[]), or 0.
static int static_noop_flag(StringArray *inputs, int i) {
  char *arg = inputs->data[i];
  char *next = (i + 1 < inputs->len) ? inputs->data[i + 1] : NULL;
  int nz = sizeof(static_noop_z) / sizeof(*static_noop_z);
  if (!strcmp(arg, "-z"))
    return (next && in_patterns(next, static_noop_z, nz)) ? 2 : 0;
  if (!strncmp(arg, "-z", 2))
    return in_patterns(arg + 2, static_noop_z, nz);
  if ((!strcmp(arg, "-rpath") || !strcmp(arg, "-rpath-link") ||
       !strcmp(arg, "--version-script") || !strcmp(arg, "--sort-section")) && next)
    return 2;
  return in_patterns(arg, static_noop_flags,
                     sizeof(static_noop_flags) / sizeof(*static_noop_flags));
}

// Links with mucc's own linker (link.c), which makes static executables.
// Returns false if it can't do this link, and `ld` must.
static bool run_builtin_linker(StringArray *inputs, char *output) {
  if (!opt_static || opt_shared || opt_system_ld)
    return false;

  // Only -L, -s, -static and the flags static_noop_flag() drops; with
  // other linker flags, use `ld`.
  StringArray lib_paths = {};
  bool strip = false;
  for (int i = 0; i < ld_extra_args.len; i++) {
    char *arg = ld_extra_args.data[i];
    if (!strcmp(arg, "-L"))
      strarray_push(&lib_paths, ld_extra_args.data[++i]);
    else if (!strcmp(arg, "-s"))
      strip = true;
    else if (strcmp(arg, "-static"))
      return false;
  }
  StringArray objs = {};
  char *map = NULL;
  for (int i = 0; i < inputs->len; i++) {
    int n = static_noop_flag(inputs, i);
    if (n) {
      i += n - 1;
      continue;
    }
    // -Map FILE: a report of where everything went, as ld writes
    char *arg = inputs->data[i];
    if ((!strcmp(arg, "-Map") || !strcmp(arg, "--Map")) && i + 1 < inputs->len) {
      map = inputs->data[++i];
      continue;
    }
    if (!strncmp(arg, "-Map=", 5) || !strncmp(arg, "--Map=", 6)) {
      map = strchr(arg, '=') + 1;
      continue;
    }
    if (!strcmp(arg, "-s") || !strcmp(arg, "--strip-all")) {
      strip = true;
      continue;
    }
    if (inputs->data[i][0] == '-' && strncmp(inputs->data[i], "-l", 2)) {
      fprintf(stderr, "mucc: note: using the system linker for %s\n",
              inputs->data[i]);
      return false;
    }
    strarray_push(&objs, inputs->data[i]);
  }

  char *libpath = find_libpath();
  char *gcc_libpath = find_gcc_libpath();
  add_library_paths(&lib_paths, gcc_libpath);

  // Objects compiled from C files are named after them in messages.
  StringArray files = {}, names = {};
  if (!opt_nostartfiles) {
    strarray_push(&files, format("%s/crt1.o", libpath));
    strarray_push(&files, format("%s/crti.o", libpath));
    push_gcc_file(&files, gcc_libpath, "crtbegin.o");
  }
  while (names.len < files.len)
    strarray_push(&names, NULL);
  for (int i = 0; i < objs.len; i++) {
    strarray_push(&files, objs.data[i]);
    strarray_push(&names, hashmap_get(&object_sources, objs.data[i]));
  }
  if (!opt_nodefaultlibs)
    push_all(&files, libc->static_libs);
  if (!opt_nostartfiles) {
    push_gcc_file(&files, gcc_libpath, "crtend.o");
    strarray_push(&files, format("%s/crtn.o", libpath));
  }
  while (names.len < files.len)
    strarray_push(&names, NULL);

  char *why;
  if (link_static(&files, &names, &lib_paths, output, strip, map, &why))
    return true;
  fprintf(stderr, "mucc: note: using the system linker (%s)\n", why);
  return false;
}

// With musl, which has no shared libraries, -lNAME must be a libNAME.a in
// a -L directory or musl's own. One that isn't is likely the system's
// (-lssl, -lz), which only --libc=system links: say so.
static void check_static_libraries(StringArray *inputs) {
  StringArray dirs = {};
  for (int i = 0; i < ld_extra_args.len; i++)
    if (!strcmp(ld_extra_args.data[i], "-L"))
      strarray_push(&dirs, ld_extra_args.data[++i]);
  push_all(&dirs, libc->lib_dirs);

  for (int i = 0; i < inputs->len; i++) {
    char *name = inputs->data[i];
    if (strncmp(name, "-l", 2))
      continue;
    bool found = false;
    for (int j = 0; j < dirs.len && !found; j++)
      found = file_exists(format("%s/lib%s.a", dirs.data[j], name + 2));
    if (!found)
      error("cannot find %s: not in -L directories or the bundled C library "
            "(--libc=system links the system's libraries)", name);
  }
}

// -r: the objects linked into one object file, with link.c's
// link_relocatable(), or by `ld -r` if it can't. Linker flags that mean
// nothing here (see static_noop_flag()) are dropped.
static void run_relocatable_link(StringArray *inputs, char *output) {
  StringArray objs = {};
  for (int i = 0; i < inputs->len; i++) {
    int n = static_noop_flag(inputs, i);
    if (n) {
      i += n - 1;
      continue;
    }
    strarray_push(&objs, inputs->data[i]);
  }

  bool plain = true;
  for (int i = 0; i < objs.len; i++)
    plain &= objs.data[i][0] != '-';
  char *why = "a linker flag";
  if (plain && !opt_system_ld && link_relocatable(&objs, output, &why))
    return;
  fprintf(stderr, "mucc: note: using the system linker (%s)\n", why);

  StringArray arr = {};
  strarray_push(&arr, "ld");
  strarray_push(&arr, "-r");
  strarray_push(&arr, "-o");
  strarray_push(&arr, output);
  for (int i = 0; i < inputs->len; i++)
    strarray_push(&arr, inputs->data[i]);
  strarray_push(&arr, NULL);
  run_subprocess(arr.data);
}

static void run_linker(StringArray *inputs, char *output) {
  if (!libc->shared_libs)
    check_static_libraries(inputs);
  if (run_builtin_linker(inputs, output))
    return;

  StringArray arr = {};

  strarray_push(&arr, "ld");
  strarray_push(&arr, "-o");
  strarray_push(&arr, output);
  strarray_push(&arr, "-m");
  strarray_push(&arr, "elf_x86_64");

  char *libpath = find_libpath();
  char *gcc_libpath = find_gcc_libpath();

  if (opt_nostartfiles) {
    // none
  } else if (opt_shared) {
    strarray_push(&arr, format("%s/crti.o", libpath));
    push_gcc_file(&arr, gcc_libpath, "crtbeginS.o");
  } else {
    strarray_push(&arr, format("%s/crt1.o", libpath));
    strarray_push(&arr, format("%s/crti.o", libpath));
    push_gcc_file(&arr, gcc_libpath, "crtbegin.o");
  }

  StringArray lib_paths = {};
  add_library_paths(&lib_paths, gcc_libpath);
  for (int i = 0; i < lib_paths.len; i++)
    strarray_push(&arr, format("-L%s", lib_paths.data[i]));

  if (!opt_static) {
    strarray_push(&arr, "-dynamic-linker");
    strarray_push(&arr, libc->dynamic_linker);
  }

  for (int i = 0; i < ld_extra_args.len; i++)
    strarray_push(&arr, ld_extra_args.data[i]);

  for (int i = 0; i < inputs->len; i++)
    strarray_push(&arr, inputs->data[i]);

  if (opt_nodefaultlibs) {
    // none
  } else if (opt_static) {
    strarray_push(&arr, "--start-group");
    push_all(&arr, libc->static_libs);
    strarray_push(&arr, "--end-group");
  } else {
    push_all(&arr, libc->shared_libs);
  }

  if (!opt_nostartfiles) {
    if (opt_shared)
      push_gcc_file(&arr, gcc_libpath, "crtendS.o");
    else
      push_gcc_file(&arr, gcc_libpath, "crtend.o");
    strarray_push(&arr, format("%s/crtn.o", libpath));
  }
  strarray_push(&arr, NULL);

  run_subprocess(arr.data);
}

//---------- main ------------------------------------------------------------

// The type of input `filename`, given `x`, the -x in effect for it.
static FileType get_file_type(char *filename, FileType x) {
  // -E implies that the input is the C macro language, or, for .S,
  // assembly with it.
  bool is_asm_cpp = (x == FILE_ASM_CPP) || (x == FILE_NONE &&
      (endswith(filename, ".S") || endswith(filename, ".sx")));
  if (opt_E)
    return is_asm_cpp ? FILE_ASM_CPP : FILE_C;
  if (x != FILE_NONE)
    return x;

  if (endswith(filename, ".a"))
    return FILE_AR;
  if (endswith(filename, ".so"))
    return FILE_DSO;
  if (endswith(filename, ".o"))
    return FILE_OBJ;
  if (endswith(filename, ".c"))
    return FILE_C;
  if (endswith(filename, ".s"))
    return FILE_ASM;
  if (endswith(filename, ".S") || endswith(filename, ".sx"))
    return FILE_ASM_CPP;

  // Sources mucc can't compile get a clear error, not a confusing one
  // from the linker.
  static char *unsupported[] = {".h", ".cc", ".cpp", ".cxx", ".C"};
  for (int i = 0; i < sizeof(unsupported) / sizeof(*unsupported); i++)
    if (endswith(filename, unsupported[i]))
      error("<command line>: unsupported file type: %s", filename);

  // Like gcc, anything else goes to the linker as an object file: libtool's
  // .lo files, versioned libraries like libfoo.so.1, and so on.
  return FILE_OBJ;
}

int main(int argc, char **argv) {
  // mucc -ar and mucc -ranlib are the archiver (ar.c).
  if (argc >= 2 && !strcmp(argv[1], "-ar"))
    return run_ar(argc - 2, argv + 2);
  if (argc >= 2 && !strcmp(argv[1], "-ranlib"))
    return run_ranlib(argc - 2, argv + 2);

  // The parser and code generator recurse as deep as code nests, and a
  // chain like `a + a + ... + a` nests as deep as it is long, so the
  // compiler, run as a new process below, gets a stack of up to 1 GB, as
  // gcc's does. Only what it uses takes memory.
  struct rlimit rl;
  if (!getrlimit(RLIMIT_STACK, &rl) && rl.rlim_cur != RLIM_INFINITY &&
      rl.rlim_cur < (1UL << 30)) {
    rl.rlim_cur = (rl.rlim_max != RLIM_INFINITY && rl.rlim_max < (1UL << 30))
                    ? rl.rlim_max : (1UL << 30);
    setrlimit(RLIMIT_STACK, &rl);
  }

  atexit(cleanup);
  set_std(argc, argv);
  init_macros();
  parse_args(argc, argv);

  if (!libc)
    libc = find_embedded(EMBED_DIR "/musl/lib/libc.a") ? &libcs[1] : &libcs[0];
  if (libc->include_dirs == musl_include_dirs)
    find_musl(argv[0]);

  // A C library with no shared libraries (musl) is always linked
  // statically.
  if (!libc->shared_libs) {
    if (opt_shared)
      error("-shared needs --libc=system");
    if (!opt_static)
      strarray_push(&ld_extra_args, "-static");
    opt_static = true;
  }

  if (opt_cc1) {
    add_default_include_paths(argv[0]);
    cc1();
    return 0;
  }

  if (input_paths.len > 1 && opt_o && (opt_c || opt_S | opt_E))
    error("cannot specify '-o' with '-c,' '-S' or '-E' with multiple files");

  StringArray ld_args = {};

  for (int i = 0; i < input_paths.len; i++) {
    char *input = input_paths.data[i];

    if (!strncmp(input, "-l", 2)) {
      strarray_push(&ld_args, input);
      continue;
    }

    if (!strncmp(input, "-Wl,", 4)) {
      char *s = strdup(input + 4);
      char *arg = strtok(s, ",");
      while (arg) {
        strarray_push(&ld_args, arg);
        arg = strtok(NULL, ",");
      }
      continue;
    }

    char *output;
    if (opt_o)
      output = opt_o;
    else if (opt_S)
      output = replace_extn(input, ".s");
    else
      output = replace_extn(input, ".o");

    FileType type = get_file_type(input, input_types[i]);

    // Handle .o, .a or .so
    if (type == FILE_DSO && !libc->shared_libs)
      error("%s: a shared library needs --libc=system", input);
    if (type == FILE_OBJ || type == FILE_AR || type == FILE_DSO) {
      strarray_push(&ld_args, input);
      continue;
    }

    // Handle .S: preprocess it as assembly, then go on as with a .s.
    if (type == FILE_ASM_CPP) {
      if (opt_E || opt_M) {
        run_cc1(argc, argv, input, NULL, false, true);
        continue;
      }
      if (opt_S)
        continue;
      char *tmp = create_tmpfile();
      run_cc1(argc, argv, input, tmp, false, true);
      input = tmp;
      type = FILE_ASM;
    }

    // Handle .s: assemble it, and link it unless -c.
    if (type == FILE_ASM) {
      if (opt_S)
        continue;
      if (opt_c) {
        assemble_file(input, output);
        continue;
      }
      char *tmp = create_tmpfile();
      assemble_file(input, tmp);
      strarray_push(&ld_args, tmp);
      continue;
    }

    assert(type == FILE_C);

    // Just preprocess
    if (opt_E || opt_M) {
      run_cc1(argc, argv, input, NULL, false, false);
      continue;
    }

    // Compile
    if (opt_S) {
      run_cc1(argc, argv, input, output, false, false);
      continue;
    }

    // Compile and assemble: cc1 writes the object itself, or writes
    // assembly for `as` with -fno-integrated-as.
    char *obj = opt_c ? output : create_tmpfile();
    if (opt_integrated_as) {
      run_cc1(argc, argv, input, obj, true, false);
    } else {
      char *tmp = create_tmpfile();
      run_cc1(argc, argv, input, tmp, false, false);
      run_as(tmp, obj);
    }

    // And link, unless -c.
    if (!opt_c) {
      strarray_push(&ld_args, obj);
      hashmap_put(&object_sources, obj, input);
    }
  }

  if (ld_args.len > 0 && opt_r) {
    run_relocatable_link(&ld_args, opt_o ? opt_o : "a.out");
    return 0;
  }

  if (ld_args.len > 0) {
    if (opt_pthread && !opt_nodefaultlibs)
      strarray_push(&ld_args, "-lpthread");
    run_linker(&ld_args, opt_o ? opt_o : "a.out");
  }
  return 0;
}
